name: 'code analyses'

on:
  pull_request:

jobs:
  code-analyses:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run check
      - run: npm run check:type
      - run: npm run lint
      - run: npm run lint:text
      - run: npm run format
      - if: ${{ !cancelled() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            ${{ job.status }}
            https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
