name: 'code analyses'

on:
  pull_request:

jobs:
  code-analyses:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - run: pnpm install --frozen-lockfile
      - run: pnpm run check:astro
      - run: pnpm run check:type
      - run: pnpm run biome:check
      - run: pnpm run lint:text
      - run: pnpm run lint:markdown
