name: 'code analyses'

on:
  pull_request:

jobs:
  code-analyses:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run check:astro
      - run: npm run check:type
      - run: npm run biome:check
      - run: npm run lint:text
      - run: npm run lint:markdown
